CREATE SCHEMA "main";

CREATE TABLE main.sites (
  "id_site" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "id_camera" int,
  "id_grid" int,
  "deployment" timestamptz,
  "id_tech" varchar,
  "settings" varchar,
  "latitude" float8,
  "longitude" float8,
  "created_at_utc" timestamptz,
  "updated_at_utc" timestamptz
);


CREATE TABLE main.cameras (
  "id_camera" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "deployment" timestamptz,
  "functioning" varchar,
  "created_at_utc"  timestamptz,
  "updated_at_utc" timestamptz
);

CREATE TABLE main.grids (
  "id_grid" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "resolution" numeric,
  "id_pasture" int,
  "id_property" int,
  "notes" varchar,
  "created_at_utc" timestamptz,
  "updated_at_utc" timestamptz
);

CREATE TABLE main.pastures (
  "id_pasture" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "id_property" numeric,
  "name" varchar,
  "created_at_utc" timestamptz,
  "updated_at_utc" timestamptz
);

CREATE TABLE main.properties (
  "id_property" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "name" varchar,
  "created_at_utc" timestamptz,
  "updated_at_utc" timestamptz
);

CREATE TABLE main.maintenance (
  "id_maintenance" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "id_site" int,
  "id_camera" int,
  "maintenance_date" timestamptz,
  "maintenance_redeployment" timestamptz,
  "notes" varchar,
  "created_at_utc" timestamptz,
  "updated_at_utc" timestamptz
);

CREATE TABLE main.photos (
  "id_photo" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "id_site" int,
  "acquisition_timestamp" timestamptz,
  "directory" varchar,
  "notes" varchar,
  "created_at_utc" timestamptz,
  "updated_at_utc" timestamptz
);

CREATE TABLE main.detections (
  "id_detection" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "id_photo" int,
  "id_species" int,
  "group_size" int,
  "notes" varchar,
  "created_at_utc" timestamptz,
  "updated_at_utc" timestamptz
);

ALTER TABLE main.sites ADD FOREIGN KEY ("id_camera") REFERENCES main.cameras ("id_camera");

ALTER TABLE main.sites ADD FOREIGN KEY ("id_grid") REFERENCES  main.grids ("id_grid");

ALTER TABLE main.grids ADD FOREIGN KEY ("id_pasture") REFERENCES main.pastures ("id_pasture");

ALTER TABLE main.grids ADD FOREIGN KEY ("id_property") REFERENCES main.properties ("id_property");

ALTER TABLE main.maintenance ADD FOREIGN KEY ("id_site") REFERENCES main.sites ("id_site");

-- ALTER TABLE "maintenance" ADD FOREIGN KEY ("id_camera") REFERENCES "sites" ("id_camera");

ALTER TABLE main.photos ADD FOREIGN KEY ("id_site") REFERENCES main.sites ("id_site");

ALTER TABLE main.detections ADD FOREIGN KEY ("id_photo") REFERENCES main.photos ("id_photo");
